[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "wordie"
authors = [{name = "Alex", email = "ajl573@bham.ac.uk"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/alexlyttle/asrcr-docs-example"
